name: PublishVLNuget
description: Publishes a VL nuget

inputs:
  NUSPEC:
    description: The path to your .nuspec file
    required: true
  SOLUTION:
    description: A path to your Visual Studio solution, if the project has any
    required: false
  ICON_SRC:
    description: An external URL for your nuget's icon, if the repo does not already have one
    required: false
  ICON_DST:
    description: If you set an external icon source, this should be the full path to the icon, as expected by your nuspec
    required: false
  VERSION:
    description: Your package's version. Must be valid semver. If not set, the version specified in your nuspec will be used
    required: false
  AUTO_PATCH_NUMBER:
    description : If true, automatically increment version patch number at each push. Otherwise, uses the input one
    default: false
  NUGET_KEY:
    description: Nuget API Key
    required: true
  NUGET_FEED:
    description: Allows to set a custom Nuget feed. If not set, assumes nuget.org default feed
    required: false
    default: 'https://api.nuget.org/v3/index.json'
  USE_SYMBOLS:
    description: Allows to explicitely use symbols when packing the nuget.
    required: false
    default: false

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: square
  color: gray-dark