name: 'Publish Nuget'
description: 'Publish your VL plugin'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  nuspec:
    description: 'The path to your .nuspec file'
    required: true
  solution:
    description: 'A path to your Visual Studio solution, if the project has any'
    required: false
  icon-src:
    description: 'An external URL for your nuget's icon, if the repo does not already have one'
    required: false
  icon-dst:
    description: 'If you set an external icon source, this should be the path where your nuspec expects the icon'
    required: false
  version:
    description: 'Uses Major.Minor.Patch format. If Patch is X, github_run_number will be used. If not set at all, nuspec file's version will be used.'
    required: false
  prerelease-flag:
    description: 'Allows to add a pre-release flag to the package. Recommanded are alpha, beta or rc but any is accepted'
    required: false
  nuget-feed:
    description: 'Allows to set a custom Nuget feed. If not set, assumes nuget.org default feed'
    required: false
    default: 'https://api.nuget.org/v3/index.json'
  use-symbols:
    description: 'Allows to explicitely use symbols when packing the nuget.'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
