name: PublishVLNuget
description: Publishes a VL nuget

inputs:
  nuspec:
    description: The path to your .nuspec file
    required: true
  solution:
    description: A path to your Visual Studio solution, if the project has any
    required: false
  icon-src:
    description: An external URL for your nuget's icon, if the repo does not already have one
    required: false
  icon-dst:
    description: If you set an external icon source, this should be the full path to the icon, as expected by your nuspec
    required: false
  version:
    description: Your package's version. Must be valid semver. If not set, the version specified in your nuspec will be used
    required: false
  auto-patch-number:
    description : If true, automatically increment version patch number at each push. Otherwise, uses the input one
    default: false
  nuget_key:
    description: Nuget API Key
    required: true
  nuget_feed:
    description: Allows to set a custom Nuget feed. If not set, assumes nuget.org default feed
    required: false
    default: 'https://api.nuget.org/v3/index.json'
  use_symbols:
    description: Allows to explicitely use symbols when packing the nuget.
    required: false
    default: false

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: square
  color: gray-dark